image: pulumi/python


.setup:
  variables:
    STACK: dev
  before_script:
    - cd infra
    - apt install python3-venv python3-pip
    - python3 -m venv venv
    - pip install -r requirements.txt
    - pulumi login --local

preview:
  stage: build
  extends: .setup
  script:
    - pulumi preview -s $STACK --non-interactive
